### ISSUE TITLE
Require is like assert ?

### ISSUE THREAD

**Issue by rob-nash** [JohnSundell/Require#3]
This is an interesting idea, but I can't help but feel it's just an alternative to the throw design paradigm.

In ScriptManager.swift (in Marathon), there is a function as follows:

```
private func script(from file: File) throws -> Script {
    let identifier = scriptIdentifier(from: file.path)
    let name = scriptName(from: identifier)
    let folder = try createFolderIfNeededForScript(withIdentifier: identifier, file: file)
    let script = Script(name: name, folder: folder, printer: printer)
    ...
}
```

The createFolderIfNeededForScript(...) function throws with useful errors but the following uses require:

```
private func scriptName(from identifier: String) -> String {
    return identifier.components(separatedBy: "-").last.require().capitalized
}
```

Would you argue that consistency is better? Therefore, using one design paradigm (throw OR require) ?
Or would you agree that require is better than writing individual error cases? 
I guess your aiming for require to primarily be used like assertion?

Force unwrap would cause a crash if the optional isn't nil. In what way does require offer more interesting feedback ? Do you have an example that you could add to the readme? You may get more stars for this repo if that aspect of this project was a little more verbose in the readme maybe.

P.S. thanks for posting interesting projects like this. It is fun stepping through your code. You write nice Swift !

**Comment by JohnSundell** [comment]
Require is very different from throwing, as it unconditionally exits the program. Thrown errors on the other hand, may be caught, handled or re-thrown. Require is to be used when there's no possible way to recover, which is usually because of faulty logic (in contrast to thrown errors, which can happen because of invalid input, for example). It's essentially just a thin wrapper around `preconditionFailure()`.

The reason `require()` is used in the example from Marathon that you gave, instead of throwing an error, is because it should never happen. If it does happen, it means that the program is in an undefined state and it's better to crash than continue.

What Require provides is a **nicer** way to crash. Using force unwrapping of optional gives you much less debug information, and makes the intent of the code unclear. Asserts are not as strict as using Require/`preconditionFailure()`, as they may be ignored in production.

I wrote a blog post on the subject a week or so ago: https://medium.com/@johnsundell/handling-non-optional-optionals-in-swift-e5706390f56f

I will make sure to add more context to the README, so that it's clear when and how to use Require 🙂

**Comment by rob-nash** [comment]
Thanks
